work6/photo_post/config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :posts, only: [:index, :new, :create, :show]
end

work6/photo_post/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  validates :title, presence: true, length: { maximum: 20 }
  validates :content, presence: true, length: { maximum: 200 }
end

work6/photo_post/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one_attached :icon
  has_many :posts, dependent: :destroy

  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true, uniqueness: true
end

work6/photo_post/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_login
    redirect_to login_path unless logged_in?
  end
end

work6/photo_post/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to posts_path, notice: "投稿が完了しました"
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :image)
  end
end

work6/photo_post/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user), notice: "ログインしました"
    else
      flash.now[:alert] = "メールアドレスまたはパスワードが正しくありません"
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to login_path, notice: "ログアウトしました"
  end
end

work6/photo_post/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:show, :edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "ユーザー登録が完了しました"
    else
      render :new
    end
  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to @user, notice: "ユーザー情報を更新しました"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :icon)
  end
end

work6/photo_post/app/views/posts/index.html.erb
<h1>投稿一覧</h1>
<p><%= link_to "新規投稿", new_post_path %></p>

<% @posts.each do |post| %>
  <div>
    <h3><%= link_to post.title, post_path(post) %></h3>
    <% if post.image.attached? %>
      <%= image_tag post.image.variant(resize_to_fill: [300, 300]) %>
    <% end %>
    <p><%= post.content.truncate(100) %></p>
  </div>
<% end %>

work6/photo_post/app/views/posts/new.html.erb
<h1>新規投稿</h1>
<%= form_with model: @post, local: true do |f| %>
  <p>タイトル: <%= f.text_field :title %></p>
  <p>内容: <%= f.text_area :content %></p>
  <p>画像: <%= f.file_field :image %></p>
  <%= f.submit "投稿" %>
<% end %>

work6/photo_post/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<% if @post.image.attached? %>
  <%= image_tag @post.image.variant(resize_to_fill: [600, 600]) %>
<% end %>
<p><%= @post.content %></p>
<p><%= link_to "一覧へ戻る", posts_path %></p>