work5/sns_site/config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  devise_for :users

  resources :posts
  resources :favorites, only: [:create, :destroy]

  resource :mypage, only: [:show, :edit, :update]

end

work5/sns_site/app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

work5/sns_site/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

work5/sns_site/app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         authentication_keys: [:name]  # ←ここでnameを指定

  validates :name, presence: true, uniqueness: true
end

work5/sns_site/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(resource)
    mypage_path
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
  end
end

work5/sns_site/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorite, only: %i[ show edit update destroy ]

  # GET /favorites or /favorites.json
  def index
    @favorites = Favorite.all
  end

  # GET /favorites/1 or /favorites/1.json
  def show
  end

  # GET /favorites/new
  def new
    @favorite = Favorite.new
  end

  # GET /favorites/1/edit
  def edit
  end

  # POST /favorites or /favorites.json
  def create
    @favorite = Favorite.new(favorite_params)

    respond_to do |format|
      if @favorite.save
        format.html { redirect_to @favorite, notice: "Favorite was successfully created." }
        format.json { render :show, status: :created, location: @favorite }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favorites/1 or /favorites/1.json
  def update
    respond_to do |format|
      if @favorite.update(favorite_params)
        format.html { redirect_to @favorite, notice: "Favorite was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @favorite }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favorites/1 or /favorites/1.json
  def destroy
    @favorite.destroy!

    respond_to do |format|
      format.html { redirect_to favorites_path, notice: "Favorite was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favorite
      @favorite = Favorite.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def favorite_params
      params.expect(favorite: [ :user_id, :post_id ])
    end
end

work5/sns_site/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

work5/sns_site/app/controllers/mypages_controller.rb
class MypagesController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to mypage_path, notice: "プロフィールを更新しました"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile, :password, :password_confirmation)
  end
end

work5/sns_site/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_path, notice: "Post was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.expect(post: [ :user_id, :content ])
    end
end

work5/sns_site/app/helpers/favorites_helper.rb
module FavoritesHelper
end

work5/sns_site/app/helpers/home_helper.rb
module HomeHelper
end

work5/sns_site/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SNSサイト</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <% if user_signed_in? %>
        <p>ログイン中: <%= current_user.name %></p>
        <nav>
          <%= link_to "マイページ", mypage_path %> |
          <%= link_to "プロフィール編集", edit_mypage_path %> |
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { turbo_confirm: "ログアウトしますか？" } %>
        </nav>
      <% else %>
        <nav>
          <%= link_to "トップ", root_path %> |
          <%= link_to "ログイン", new_user_session_path, data: { turbo: false } %> |
          <%= link_to "新規登録", new_user_registration_path, data: { turbo: false } %>
        </nav>
      <% end %>
    </header>

    <main>
      <%= yield %>
    </main>
  </body>
</html>

work5/sns_site/app/views/mypages/edit.html.erb
<h2>プロフィール編集</h2>

<%= form_with(model: @user, url: mypage_path, method: :patch) do |f| %>
  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :profile, "自己紹介" %><br>
    <%= f.text_area :profile %>
  </div>

  <div>
    <%= f.label :password %> (変更する場合のみ)<br>
    <%= f.password_field :password, autocomplete: "new-password" %>
  </div>

  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>

  <div>
    <%= f.submit "更新" %>
  </div>
<% end %>

<%= link_to "マイページに戻る", mypage_path %>

work5/sns_site/app/views/mypages/show.html.erb
<h2>マイページ</h2>
<p>名前: <%= @user.name %></p>
<p>自己紹介: <%= @user.profile %></p>

<%= link_to "編集", edit_mypage_path %> |
<%= link_to "トップに戻る", root_path %> |
<%= link_to "ログアウト", destroy_user_session_path, method: :delete %>

work5/sns_site/app/views/mypages/update.html.erb
<h1>Mypages#update</h1>
<p>Find me in app/views/mypages/update.html.erb</p>

work5/sns_site/app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.textarea :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

work5/sns_site/app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <div>
    <strong>User:</strong>
    <%= post.user_id %>
  </div>

  <div>
    <strong>Content:</strong>
    <%= post.content %>
  </div>

</div>

work5/sns_site/app/views/posts/edit.html.erb
<% content_for :title, "Editing post" %>

<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

work5/sns_site/app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Posts" %>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

work5/sns_site/app/views/posts/new.html.erb
<% content_for :title, "New post" %>

<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

work5/sns_site/app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>